// Centralized icon filter sets for reuse across components
export const DEMO_FILTERS: Record<string, string[] | undefined> = {
  All: undefined,
  Essentials: [
    "bag",
    "calendar",
    "check",
    "clock",
    "list",
    "send",
    "settings",
    "shoppingCart",
    "plus",
    "edit",
    "repeat",
    "trash",
    "split",
    "right",
    "left",
    "up",
    "down",
    "user",
    "notifications",
    "other",
    "prefrences",
    "study",
    "goals",
    "skills",
    "medal",
    "trophy",
    "highEffort",
    "lowEffort",
    "highPriority",
    "mediumPiority",
    "mediumImportant",
    "lowImportant",
    "cancel",
  ],
  Wellness: ["health", "mindfulness", "workout", "heart", "flame"],
  Creative: [
    "creative",
    "hobbies",
    "puzzle",
    "explore",
    "burger",
    "move",
    "reflection",
    "mojo",
    "ojo",
    "friends",
    "family",
    "mentorjo",
    "bestojo",
    "brojo",
    "strictojo",
    "random",
    "default",
  ],
};
