/**
 * CreateTask Screen
 *
 * A comprehensive task creation form that allows users to:
 * - Enter task name and description
 * - Set time to complete (with date picker)
 * - Adjust effort and importance using sliders
 * - Select a task category from a dropdown
 * - Add/remove task tags
 * - View task statistics (effort, time, participants)
 *
 * Uses existing UI components: Input, Slider, AppButton, Box, AppText, and ScrollableContent.
 *
 * Usage:
 * ```tsx
 * // In navigation or parent component
 * <CreateTask />
 * ```
 */

import React, { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { View, StyleSheet, ScrollView, Pressable, Modal, Alert } from "react-native";
import { COLORS, SPACING, TYPOGRAPHY, SHADOWS, FONT_SIZES } from "../theme";
import { useColors } from "../context/ThemeContext";
import AppText from "../components/common/AppText";
import AppButton from "../components/common/AppButton";
import Input from "../components/inputs/Input";
import SliderComponent from "../components/inputs/Slider";
import CalendarPicker from "../components/inputs/CalendarPicker";
import Box from "../components/layout/Box";
import { ICONS } from "../components/icons/icons";
import NavBar from "../components/common/NavBar";
import { CATEGORY_KEYS, getCategoryMeta, CATEGORY_META } from "../config/categoryMeta";
import { createTask, suggestCategory } from "../services/taskService";
import { useNavigation } from "../context/NavigationContext";

interface Subtask {
  id: string;
  title: string;
  description: string;
  minutes: string; // estimated minutes for this subtask
  index?: number; // order within the parent task (set automatically)
}

interface TaskFormState {
  taskName: string;
  timeToComplete: string;
  effort: number;
  importance: number;
  category: string;
  tags: string[];
  description: string;
  estimatedMinutes: string;
  numSubtasks: number;
  subtasks: Subtask[];
}

/**
 * CreateTask Screen Component
 *
 * Main screen for creating new tasks with comprehensive form fields.
 */
const CreateTask: React.FC = () => {
  const { setHeaderConfig } = useNavigation();
  const colors = useColors();

  const [formState, setFormState] = useState<TaskFormState>({
    taskName: "",
    timeToComplete: "",
    effort: 3,
    importance: 3,
    category: CATEGORY_KEYS[0] || "uncategorized",
    tags: [],
    description: "",
    estimatedMinutes: "",
    numSubtasks: 1,
    subtasks: [],
  });

  const [tagInput, setTagInput] = useState("");
  const [isCategoryModalVisible, setIsCategoryModalVisible] = useState(false);
  const [isCalendarModalVisible, setIsCalendarModalVisible] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // Ref to track if category was manually changed by user
  const categoryManuallyChanged = useRef(false);
  // Ref to track the auto-generated subcategory tag
  const autoGeneratedTag = useRef<string | null>(null);

  // Hide the NavigationContext header since CreateTask has its own built-in header
  useEffect(() => {
    setHeaderConfig({
      show: false,
    });
  }, [setHeaderConfig]);

  // Debounced autofill for category and subcategory based on task name
  useEffect(() => {
    if (!formState.taskName.trim()) {
      return; // Don't autofill if task name is empty
    }

    // Reset manual change flag when task name changes (allow autofill for new name)
    categoryManuallyChanged.current = false;

    const timeoutId = setTimeout(async () => {
      try {
        console.log("🔄 Autofill triggered for task name:", formState.taskName);
        console.log("📋 Current tags before autofill:", formState.tags);

        const suggestion = await suggestCategory(formState.taskName);
        console.log("💡 Suggestion received:", suggestion);

        if (suggestion && !categoryManuallyChanged.current) {
          // First, clear all tags and update category in one state update
          const newTags = suggestion.subCategory ? [suggestion.subCategory] : [];
          console.log("✨ Clearing all tags and setting to:", newTags);

          setFormState((prev) => ({
            ...prev,
            category: suggestion.category,
            tags: newTags, // This completely replaces the tags array
          }));

          // Update the auto-generated tag reference
          autoGeneratedTag.current = suggestion.subCategory || null;
        }
      } catch (error) {
        console.warn("Failed to auto-suggest category:", error);
      }
    }, 800); // Debounce for 800ms

    return () => clearTimeout(timeoutId);
  }, [formState.taskName]);

  // Get category display names for dropdown options
  const categoryOptions = useMemo(() => CATEGORY_KEYS.map((key) => CATEGORY_META[key]?.displayName || key), []);

  // Get current category metadata
  const currentCategoryMeta = getCategoryMeta(formState.category);

  /**
   * Handle task name input change
   */
  const handleTaskNameChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, taskName: text }));
  }, []);

  /**
   * Handle time to complete input change
   */
  const handleTimeToCompleteChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: text }));
  }, []);

  /**
   * Handle date selection from calendar picker
   */
  const handleDateSelect = useCallback((date: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: date }));
    setIsCalendarModalVisible(false);
  }, []);

  /**
   * Handle estimated minutes input change
   */
  const handleEstimatedMinutesChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, estimatedMinutes: text }));
  }, []);

  /**
   * Handle number of subtasks change
   */
  const handleNumSubtasksChange = useCallback(
    (value: number) => {
      if (value < 1) value = 1;
      if (value > 10) value = 10; // limit to 10 subtasks

      const currentSubtasks = formState.subtasks;
      const newSubtasks: Subtask[] = [];

      // Keep existing subtasks and add new ones if needed
      for (let i = 0; i < value; i++) {
        if (currentSubtasks[i]) {
          newSubtasks.push(currentSubtasks[i]);
        } else {
          newSubtasks.push({
            id: `subtask-${i}-${Date.now()}`,
            title: "",
            description: "",
            minutes: "",
            index: i + 1,
          });
        }
      }

      setFormState((prev) => ({ ...prev, numSubtasks: value, subtasks: newSubtasks }));
    },
    [formState.subtasks],
  );

  /**
   * Update a specific subtask
   */
  const updateSubtask = useCallback((index: number, field: keyof Subtask, value: any) => {
    setFormState((prev) => {
      const updatedSubtasks = [...prev.subtasks];
      updatedSubtasks[index] = {
        ...updatedSubtasks[index],
        [field]: value,
      };
      return { ...prev, subtasks: updatedSubtasks };
    });
  }, []);

  /**
   * Handle effort slider change
   */
  const handleEffortChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, effort: value }));
  }, []);

  /**
   * Handle importance slider change
   */
  const handleImportanceChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, importance: value }));
  }, []);

  /**
   * Handle category selection
   */
  const handleCategorySelect = useCallback((categoryKey: string) => {
    categoryManuallyChanged.current = true; // Mark as manually changed
    setFormState((prev) => ({ ...prev, category: categoryKey }));
    setIsCategoryModalVisible(false);
  }, []);

  /**
   * Handle description input change
   */
  const handleDescriptionChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, description: text }));
  }, []);

  /**
   * Add a tag to the tag list
   */
  const handleAddTag = useCallback(() => {
    if (tagInput.trim() && !formState.tags.includes(tagInput.trim())) {
      setFormState((prev) => ({
        ...prev,
        tags: [...prev.tags, tagInput.trim()],
      }));
      setTagInput("");
    }
  }, [tagInput, formState.tags]);

  /**
   * Remove a tag from the tag list
   */
  const handleRemoveTag = useCallback((tagToRemove: string) => {
    setFormState((prev) => ({
      ...prev,
      tags: prev.tags.filter((tag) => tag !== tagToRemove),
    }));
  }, []);

  /**
   * Handle form submission - Create task via API
   */
  const handleCreateTask = useCallback(async () => {
    // Validate required fields
    if (!formState.taskName.trim()) {
      Alert.alert("Validation Error", "Please enter a task name");
      return;
    }

    if (!formState.timeToComplete.trim()) {
      Alert.alert("Validation Error", "Please select a date to complete");
      return;
    }

    setIsLoading(true);
    try {
      // Prepare subtasks data
      const subtasksData = formState.subtasks
        .filter((st) => st.title.trim()) // Only include subtasks with titles
        .map((st) => ({
          title: st.title,
          description: st.description || undefined,
          minutes: st.minutes ? parseInt(st.minutes, 10) : undefined,
        }));

      // Determine task type based on number of parts and time distribution
      let taskType: "perfect" | "in_parts" | "leaky" = "perfect";
      let chunkCount: number | undefined = undefined;

      if (formState.numSubtasks > 1) {
        // Check if subtasks have different durations (leaky task)
        const subtaskMinutes = formState.subtasks
          .map((st) => (st.minutes ? parseInt(st.minutes, 10) : 0))
          .filter((m) => m > 0);

        if (subtaskMinutes.length >= 2) {
          // Check if all minutes are the same
          const allSame = subtaskMinutes.every((m) => m === subtaskMinutes[0]);
          taskType = allSame ? "in_parts" : "leaky";
        } else {
          // No specific minutes set, default to in_parts
          taskType = "in_parts";
        }
        chunkCount = formState.numSubtasks;
      }

      // Create task payload
      const taskPayload = {
        taskname: formState.taskName,
        description: formState.description || undefined,
        category: formState.category,
        importance: formState.importance,
        effort: formState.effort,
        deadline: formState.timeToComplete, // Backend expects 'deadline' not 'dueDate'
        estimatedMinutes: formState.estimatedMinutes ? parseInt(formState.estimatedMinutes, 10) : undefined,
        tags: formState.tags.length > 0 ? formState.tags : undefined,
        subtasks: subtasksData.length > 0 ? subtasksData : undefined,
        taskType,
        chunkCount,
      };

      console.log("=== CREATING TASK ===");
      console.log("Payload:", JSON.stringify(taskPayload, null, 2));

      // Call API to create task
      const result = await createTask(taskPayload);

      console.log("=== TASK CREATED ===");
      console.log("Result:", JSON.stringify(result, null, 2));

      if (result) {
        Alert.alert("Success!", "Task created successfully", [
          {
            text: "OK",
            onPress: () => {
              // Reset form after success
              setFormState({
                taskName: "",
                timeToComplete: "",
                effort: 3,
                importance: 3,
                category: CATEGORY_KEYS[0] || "uncategorized",
                tags: [],
                description: "",
                estimatedMinutes: "",
                numSubtasks: 1,
                subtasks: [],
              });
              setTagInput("");
            },
          },
        ]);
      } else {
        Alert.alert("Error", "Failed to create task. Please try again.");
      }
    } catch (error) {
      console.error("=== ERROR CREATING TASK ===");
      console.error("Error details:", error);
      Alert.alert("Error", `Failed to create task: ${error instanceof Error ? error.message : "Unknown error"}`);
    } finally {
      setIsLoading(false);
    }
  }, [formState]);

  /**
   * Get color based on importance value
   */
  const getImportanceColor = (value: number): string => {
    if (value === 1) return COLORS.primary6; // Green - Low
    if (value === 2) return "#2196F3"; // Blue - Below Avg
    if (value === 3) return COLORS.primary5; // Orange - Average
    if (value === 4) return COLORS.primary4; // Pink - Above Avg
    return "#D32F2F"; // Red - Critical
  };

  return (
    <View style={styles.container}>
      {/* Sticky Header Section */}
      <View style={styles.headerSection}>
        <AppText variant="title2" style={styles.mainTitle}>
          + CREATE A TASK
        </AppText>
      </View>

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.contentContainer}>
        {/* Task Details Box */}
        <Box title="TASK DETAILS" style={styles.boxContent}>
          {/* Task Name Input */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Task Name</AppText>
            <Input placeholder="Your Task" value={formState.taskName} onChangeText={handleTaskNameChange} type="text" />
          </View>

          {/* Time to Complete Input with Calendar Icon */}
          <View style={styles.formField}>
            <View style={styles.timeToCompleteLabelContainer}>
              <AppText style={styles.label}>Time to Complete</AppText>
            </View>
            <View style={styles.timeToCompleteWrapper}>
              <View style={styles.timeToCompleteInputContainer}>
                <Input
                  placeholder="Your Task"
                  value={formState.timeToComplete}
                  onChangeText={handleTimeToCompleteChange}
                  type="text"
                  editable={false}
                />
                <Pressable
                  style={styles.calendarButton}
                  onPress={() => setIsCalendarModalVisible(!isCalendarModalVisible)}
                >
                  {ICONS.calendar &&
                    React.createElement(ICONS.calendar, {
                      size: 24,
                      color: COLORS.primary1,
                    })}
                </Pressable>
              </View>

              {/* Inline Calendar Dropdown */}
              {isCalendarModalVisible && (
                <View style={styles.inlineCalendarContainer}>
                  <CalendarPicker onDateSelect={handleDateSelect} selectedDate={formState.timeToComplete} />
                </View>
              )}
            </View>
          </View>

          {/* Effort and Importance Sliders */}
          <View style={styles.slidersContainer}>
            <View style={[styles.sliderWrapper, { flex: 1, marginRight: SPACING.md }]}>
              <SliderComponent
                value={formState.effort}
                onValueChange={handleEffortChange}
                min={1}
                max={5}
                step={1}
                label="Effort"
                trackColor={COLORS.lightGray}
                TrackThumbColor={getImportanceColor(formState.effort)}
                valueDescriptions={{
                  1: "Very Easy",
                  2: "Easy",
                  3: "Moderate",
                  4: "Hard",
                  5: "Very Hard",
                }}
              />
            </View>

            <View style={[styles.sliderWrapper, { flex: 1 }]}>
              <SliderComponent
                value={formState.importance}
                onValueChange={handleImportanceChange}
                min={1}
                max={5}
                step={1}
                label="Importance"
                trackColor={COLORS.lightGray}
                TrackThumbColor={getImportanceColor(formState.importance)}
                valueDescriptions={{
                  1: "Low",
                  2: "Below Avg",
                  3: "Average",
                  4: "Above Avg",
                  5: "Critical",
                }}
              />
            </View>
          </View>

          {/* Task Category Dropdown */}
          <View style={styles.formField}>
            <View style={styles.categoryLabelContainer}>
              <AppText style={styles.label}>Task Category</AppText>
            </View>
            <Pressable style={styles.categoryButton} onPress={() => setIsCategoryModalVisible(true)}>
              <View style={styles.categoryContent}>
                <View style={[styles.categoryIcon, { backgroundColor: currentCategoryMeta.color }]}>
                  {ICONS[currentCategoryMeta.icon] &&
                    React.createElement(ICONS[currentCategoryMeta.icon], {
                      size: 20,
                      color: COLORS.white,
                    })}
                </View>
                <AppText style={styles.categoryText}>{currentCategoryMeta.displayName}</AppText>
              </View>
              <View style={styles.dropdownChevron}>
                {ICONS.down &&
                  React.createElement(ICONS.down, {
                    size: 20,
                    color: COLORS.lightGray,
                  })}
              </View>
            </Pressable>
          </View>

          {/* Task Tags Section */}
          <View style={styles.formField}>
            <View style={styles.tagsLabelContainer}>
              <AppText style={styles.label}>Task Tags</AppText>
            </View>

            <View style={styles.tagInputContainer}>
              <Input placeholder="Your name" value={tagInput} onChangeText={setTagInput} type="text" />
              <Pressable style={styles.addTagButton} onPress={handleAddTag}>
                <AppText variant="title3" style={styles.addTagButtonText}>
                  +
                </AppText>
              </Pressable>
            </View>

            {/* Rendered Tags */}
            {formState.tags.length > 0 && (
              <View style={styles.tagsDisplay}>
                {formState.tags.map((tag, index) => (
                  <Pressable key={`${tag}-${index}`} style={styles.tag} onPress={() => handleRemoveTag(tag)}>
                    <AppText style={styles.tagText}>{tag}</AppText>
                    <AppText style={styles.tagCloseIcon}> ✕</AppText>
                  </Pressable>
                ))}
              </View>
            )}
          </View>

          {/* Task Description Textarea */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Task Description</AppText>
            <Input
              placeholder="Your Task"
              value={formState.description}
              onChangeText={handleDescriptionChange}
              type="longtext"
              multiline
              numberOfLines={6}
            />
          </View>
        </Box>

        {/* Additional Task Details Box */}
        <Box title="ADDITIONAL DETAILS" style={styles.boxContent}>
          {/* Estimated Minutes Input */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Estimated Minutes</AppText>
            <Input
              placeholder="e.g., 30"
              value={formState.estimatedMinutes}
              onChangeText={handleEstimatedMinutesChange}
              type="number"
            />
          </View>

          {/* Number of Subtasks */}
          <View style={styles.formField}>
            <AppText style={styles.label}>Split Task Into Parts</AppText>
            <View style={styles.subtaskCounterContainer}>
              <Pressable
                style={styles.counterButton}
                onPress={() => handleNumSubtasksChange(Math.max(1, formState.numSubtasks - 1))}
              >
                <AppText style={styles.counterButtonText}>−</AppText>
              </Pressable>
              <View style={styles.counterDisplay}>
                <AppText style={styles.counterText}>{formState.numSubtasks}</AppText>
              </View>
              <Pressable
                style={styles.counterButton}
                onPress={() => handleNumSubtasksChange(formState.numSubtasks + 1)}
              >
                <AppText style={styles.counterButtonText}>+</AppText>
              </Pressable>
            </View>
          </View>

          {/* Subtasks Section - Only show if numSubtasks >= 2 */}
          {formState.numSubtasks >= 2 && (
            <View style={styles.subtasksSection}>
              <AppText style={[styles.label, { marginBottom: SPACING.md }]}>Define Subtasks</AppText>
              {formState.subtasks.map((subtask, index) => (
                <View key={subtask.id} style={styles.subtaskCard}>
                  <AppText style={styles.subtaskHeader}>Part {index + 1}</AppText>

                  {/* Subtask Title */}
                  <View style={styles.formField}>
                    <AppText style={styles.customLabel}>Part Name</AppText>
                    <Input
                      placeholder="e.g., Planning"
                      value={subtask.title}
                      onChangeText={(text) => updateSubtask(index, "title", text)}
                      type="text"
                    />
                  </View>

                  {/* Subtask Description */}
                  <View style={styles.formField}>
                    <AppText style={styles.customLabel}>Part Description</AppText>
                    <Input
                      placeholder="Describe this part..."
                      value={subtask.description}
                      onChangeText={(text) => updateSubtask(index, "description", text)}
                      type="longtext"
                      multiline
                      numberOfLines={2}
                    />
                  </View>

                  {/* Subtask Estimated Minutes */}
                  <View style={styles.formField}>
                    <Input
                      label="Estimated Minutes"
                      placeholder="e.g., 15"
                      value={subtask.minutes}
                      onChangeText={(text) => updateSubtask(index, "minutes", text)}
                      type="number"
                    />
                  </View>
                </View>
              ))}
            </View>
          )}
        </Box>

        {/* Create Task Button */}
        <View style={styles.buttonContainer}>
          <AppButton
            title={isLoading ? "CREATING..." : "CREATE TASK"}
            onPress={handleCreateTask}
            mode="filled"
            color="#2ecc71"
            icon={isLoading ? undefined : "plus"}
            iconPosition="right"
            width="100%"
            disabled={isLoading}
          />
        </View>
      </ScrollView>

      {/* Sticky NavBar at Bottom */}
      <NavBar />

      {/* Category Selection Modal */}
      <Modal
        visible={isCategoryModalVisible}
        transparent
        animationType="fade"
        onRequestClose={() => setIsCategoryModalVisible(false)}
      >
        <Pressable style={styles.modalOverlay} onPress={() => setIsCategoryModalVisible(false)}>
          <View style={styles.modalContent}>
            <AppText variant="title3" style={styles.modalTitle}>
              Select Category
            </AppText>
            <ScrollView style={styles.categoryList}>
              {CATEGORY_KEYS.map((categoryKey) => {
                const meta = getCategoryMeta(categoryKey);
                const isSelected = formState.category === categoryKey;
                return (
                  <Pressable
                    key={categoryKey}
                    style={[styles.categoryOption, isSelected && styles.categoryOptionSelected]}
                    onPress={() => handleCategorySelect(categoryKey)}
                  >
                    <View style={styles.categoryOptionContent}>
                      <View style={[styles.categoryOptionIcon, { backgroundColor: meta.color }]}>
                        {ICONS[meta.icon] &&
                          React.createElement(ICONS[meta.icon], {
                            size: 24,
                            color: COLORS.white,
                          })}
                      </View>
                      <AppText style={styles.categoryOptionText}>{meta.displayName}</AppText>
                    </View>
                    {isSelected && (
                      <View style={styles.checkmark}>
                        <AppText style={styles.checkmarkText}>✓</AppText>
                      </View>
                    )}
                  </Pressable>
                );
              })}
            </ScrollView>
          </View>
        </Pressable>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  contentContainer: {
    padding: SPACING.sm,
    paddingBottom: SPACING.md,
  },
  headerSection: {
    paddingTop: SPACING.xlg,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
    borderBottomLeftRadius: SPACING.xlg,
    borderBottomRightRadius: SPACING.xlg,
    ...(SHADOWS.card as object),
    zIndex: 100,
    backgroundColor: COLORS.white,
  },
  mainTitle: {
    color: COLORS.primary1,
    fontWeight: "400",
  },
  boxContent: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    overflow: "visible",
  },
  formField: {
    marginBottom: SPACING.sm,
    overflow: "visible",
  },
  slidersContainer: {
    flexDirection: "row",
    marginBottom: SPACING.sm,
    gap: SPACING.sm,
  },
  sliderWrapper: {
    gap: SPACING.sm,
  },
  sliderLabel: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  label: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  customLabel: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  categoryLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: 4,
  },
  timeToCompleteLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: 4,
  },
  timeToCompleteInputContainer: {
    position: "relative",
    marginBottom: 3,
  },
  timeToCompleteWrapper: {
    overflow: "visible",
  },
  inlineCalendarContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
    overflow: "hidden",
    ...SHADOWS.card,
  },
  inlineCalendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.brightP1,
  },
  inlineCalendarTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "400",
    color: COLORS.primary1,
  },
  inlineCalendarClose: {
    fontSize: FONT_SIZES.lg,
    color: COLORS.darkGray,
    fontWeight: "400",
  },
  inlineCalendarContent: {
    padding: SPACING.md,
    minHeight: 250,
    justifyContent: "center",
    alignItems: "center",
  },
  inlineCalendarPlaceholder: {
    color: COLORS.lightGray,
    fontSize: FONT_SIZES.md,
  },
  calendarButton: {
    position: "absolute",
    right: SPACING.sm,
    top: "50%",
    transform: [{ translateY: -22 }],
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  categoryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderWidth: 0.15,
    borderColor: COLORS.brightP1,
    minHeight: 52,
  },
  categoryContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  categoryIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  categoryText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.darkGray,
    fontWeight: "500",
  },
  dropdownChevron: {
    justifyContent: "center",
    alignItems: "center",
  },
  subtaskCounterContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginTop: SPACING.sm,
  },
  counterButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: COLORS.primary1,
    justifyContent: "center",
    alignItems: "center",
  },
  counterButtonText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.lg,
    fontWeight: "bold",
  },
  counterDisplay: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    alignItems: "center",
    ...SHADOWS.card,
  },
  counterText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "600",
    color: COLORS.primary1,
  },
  subtasksSection: {
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  subtaskCard: {
    backgroundColor: COLORS.white2,
    borderRadius: 12,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary1,
  },
  subtaskHeader: {
    fontSize: FONT_SIZES.md,
    fontWeight: "600",
    color: COLORS.primary1,
    marginBottom: SPACING.md,
  },
  tagsLabelContainer: {
    // marginBottom: 1,
  },
  tagInputContainer: {
    position: "relative",
    marginBottom: 3,
  },
  addTagButton: {
    position: "absolute",
    right: SPACING.sm,
    top: "50%",
    transform: [{ translateY: -22 }],
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  addTagButtonText: {
    color: COLORS.primary1,
    fontSize: FONT_SIZES.md,
    fontWeight: "bold",
  },
  tagsDisplay: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginTop: 3,
  },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFB6D9",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: SPACING.md,
    ...SHADOWS.card,
  },
  tagText: {
    color: "#C2185B",
    fontWeight: "500",
    marginRight: SPACING.sm,
  },
  tagCloseIcon: {
    color: "#C2185B",
    fontWeight: "bold",
  },
  taskPartsGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: SPACING.lg,
  },
  taskPartItem: {
    alignItems: "center",
    gap: SPACING.sm,
  },
  taskPartIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: COLORS.white3,
    justifyContent: "center",
    alignItems: "center",
  },
  taskPartLabel: {
    textAlign: "center",
    fontSize: FONT_SIZES.sm,
    color: COLORS.darkGray,
    maxWidth: 80,
  },
  buttonContainer: {
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    width: "85%",
    maxHeight: "70%",
    paddingVertical: SPACING.lg,
    ...SHADOWS.card,
  },
  modalTitle: {
    textAlign: "center",
    color: COLORS.primary1,
    fontWeight: "400",
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  categoryList: {
    paddingHorizontal: SPACING.md,
  },
  categoryOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: 12,
    marginBottom: SPACING.sm,
  },
  categoryOptionSelected: {
    backgroundColor: COLORS.white2,
  },
  categoryOptionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  categoryOptionIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  categoryOptionText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.darkGray,
    fontWeight: "500",
  },
  checkmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.primary1,
    justifyContent: "center",
    alignItems: "center",
  },
  checkmarkText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.md,
    fontWeight: "400",
  },
  calendarModalContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  calendarModalHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  calendarModalCloseText: {
    fontSize: FONT_SIZES.lg,
    color: COLORS.darkGray,
    fontWeight: "400",
  },
});

export default CreateTask;
