/**
 * EditTask Screen
 *
 * A comprehensive task editing form that allows users to:
 * - Edit task name and description
 * - Modify time to complete (with date picker)
 * - Adjust effort and importance using sliders
 * - Change task category from a dropdown
 * - Add/remove task tags
 * - View task statistics (effort, time, participants)
 *
 * Uses existing UI components: Input, Slider, AppButton, Box, AppText, and ScrollableContent.
 *
 * Usage:
 * ```tsx
 * // In navigation or parent component
 * <EditTask />
 * ```
 */

import React, { useState, useCallback, useEffect, useRef } from "react";
import { View, StyleSheet, ScrollView, Pressable, SafeAreaView, TouchableOpacity, ActivityIndicator } from "react-native";
import { COLORS, SPACING, TYPOGRAPHY, SHADOWS, FONT_SIZES, ICON_SIZES } from "../theme";
import AppText from "../components/common/AppText";
import AppButton from "../components/common/AppButton";
import Input from "../components/inputs/Input";
import SliderComponent from "../components/inputs/Slider";
import CalendarPicker from "../components/inputs/CalendarPicker";
import Box from "../components/layout/Box";
import { ICONS } from "../components/icons/icons";
import CategoryPicker from "../components/special/CategoryPicker";
import TagsBelow from "../components/inputs/TagsBelow";
import PopupBox from "../components/common/PopupBox";
import { getTaskById, updateTask, deleteTask, suggestCategory } from "../services/taskService";
import { getImportanceColor } from "../components/widgets/taskHelpers";
import { useNavigation } from "../context/NavigationContext";
import { useTaskContext } from "../context/TaskContext";
import { useLayout } from "../context/LayoutContext";

const NAVBAR_HEIGHT = 96;

interface Subtask {
  id: string;
  title: string;
  description: string;
  minutes: string; // estimated minutes for this subtask
  index?: number; // order within the parent task (set automatically)
}

interface TaskFormState {
  taskName: string;
  timeToComplete: string;
  effort: number;
  importance: number;
  category: string;
  tags: string[];
  description: string;
  estimatedMinutes: string;
  numSubtasks: number;
  subtasks: Subtask[];
}

/**
 * EditTask Screen Component
 *
 * Main screen for editing existing tasks with comprehensive form fields.
 *
 * @param {object} props - Component props
 * @param {string} props.taskId - The ID of the task to edit
 */
const EditTask: React.FC<{ taskId?: string }> = ({ taskId = "" }) => {
  const { setHeaderConfig, setActiveTab } = useNavigation();
  const { notifyTaskUpdate } = useTaskContext();

  const [formState, setFormState] = useState<TaskFormState>({
    taskName: "",
    timeToComplete: "",
    effort: 3,
    importance: 3,
    category: "",
    tags: [],
    description: "",
    estimatedMinutes: "",
    numSubtasks: 1,
    subtasks: [],
  });

  const [tagInput, setTagInput] = useState("");
  const [isCalendarModalVisible, setIsCalendarModalVisible] = useState(false);
  const [popupInfo, setPopupInfo] = useState<{
    title: string;
    message: string;
    navigateOnClose?: boolean;
    confirmAction?: () => void;
  } | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isFetching, setIsFetching] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);

  // Ref to track if category was manually changed by user
  const categoryManuallyChanged = useRef(false);
  // Ref to track the auto-generated subcategory tag
  const autoGeneratedTag = useRef<string | null>(null);
  // Ref to track if we've loaded the task data (prevent autofill overwriting loaded data)
  const hasLoadedTask = useRef(false);

  // Use the shared Header via NavigationContext so spacing matches other screens
  useEffect(() => {
    const handleBackPress = () => {
      setActiveTab("calendar");
    };

    setHeaderConfig({
      title: "Edit Task",
      show: true,
      icon: ICONS.edit,
      leftElement: (
        <TouchableOpacity onPress={handleBackPress} style={styles.headerIconButton}>
          {ICONS.left && React.createElement(ICONS.left, { size: ICON_SIZES.md, color: COLORS.primary1 })}
        </TouchableOpacity>
      ),
      rightElement: (
        <View style={styles.headerRight}>
          {ICONS.edit && React.createElement(ICONS.edit, { size: ICON_SIZES.md, color: COLORS.primary1 })}
        </View>
      ),
    });

    return () => {
      // Clean up: hide header for other flows that expect no header
      setHeaderConfig({ show: false });
    };
  }, [setHeaderConfig, setActiveTab]);

  // Load task data from API when the screen mounts or taskId changes
  useEffect(() => {
    if (!taskId) {
      setIsFetching(false);
      setFetchError("No task ID provided.");
      return;
    }

    let cancelled = false;

    const loadTask = async () => {
      setIsFetching(true);
      setFetchError(null);
      try {
        const task = await getTaskById(taskId);
        if (cancelled) return;

        if (!task) {
          setFetchError("Task not found.");
          setIsFetching(false);
          return;
        }

        // Extract date portion from dueDate (YYYY-MM-DD)
        let dateStr = "";
        if (task.dueDate) {
          const d = new Date(task.dueDate);
          dateStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
        }

        // Build subtask form state from API subtasks
        const apiSubtasks = task.subtasks || (task as any).subTasks || [];
        const formSubtasks: Subtask[] = apiSubtasks.map((st: any, idx: number) => ({
          id: st._id || st.id || `subtask-${idx}-${Date.now()}`,
          title: st.title || "",
          description: st.description || "",
          minutes: st.minutes ? String(st.minutes) : "",
          index: st.index ?? idx + 1,
        }));

        const numSubtasks = formSubtasks.length > 0 ? formSubtasks.length : 1;

        // Build tags from task.tags
        const tags: string[] = [];
        if (task.tags && Array.isArray(task.tags)) {
          tags.push(...task.tags);
        }

        setFormState({
          taskName: task.taskname || "",
          timeToComplete: dateStr,
          effort: task.effort ?? 3,
          importance: task.importance ?? 3,
          category: task.category || "",
          tags,
          description: task.description || "",
          estimatedMinutes: task.estimatedDuration ? String(task.estimatedDuration) : "",
          numSubtasks,
          subtasks: formSubtasks,
        });

        hasLoadedTask.current = true;
        categoryManuallyChanged.current = true; // Prevent autofill from overwriting loaded category
      } catch (error) {
        if (!cancelled) {
          setFetchError(error instanceof Error ? error.message : "Failed to load task.");
        }
      } finally {
        if (!cancelled) {
          setIsFetching(false);
        }
      }
    };

    loadTask();

    return () => {
      cancelled = true;
    };
  }, [taskId]);

  // Debounced autofill for category and subcategory based on task name
  // Only runs when user manually changes the task name (not during initial load)
  useEffect(() => {
    if (!formState.taskName.trim() || !hasLoadedTask.current) {
      return; // Don't autofill if task name is empty or we haven't loaded yet
    }

    // Don't autofill if category was manually changed or set by loading
    if (categoryManuallyChanged.current) {
      return;
    }

    const timeoutId = setTimeout(async () => {
      try {
        console.log("🔄 Autofill triggered for task name:", formState.taskName);
        console.log("📋 Current tags before autofill:", formState.tags);

        const suggestion = await suggestCategory(formState.taskName);
        console.log("💡 Suggestion received:", suggestion);

        if (suggestion && !categoryManuallyChanged.current) {
          // First, clear all tags and update category in one state update
          const newTags = suggestion.subCategory ? [suggestion.subCategory] : [];
          console.log("✨ Clearing all tags and setting to:", newTags);

          setFormState((prev) => ({
            ...prev,
            category: suggestion.category,
            tags: newTags, // This completely replaces the tags array
          }));

          // Update the auto-generated tag reference
          autoGeneratedTag.current = suggestion.subCategory || null;
        }
      } catch (error) {
        console.warn("Failed to auto-suggest category:", error);
      }
    }, 800); // Debounce for 800ms

    return () => clearTimeout(timeoutId);
  }, [formState.taskName]);

  /**
   * Handle task name input change
   */
  const handleTaskNameChange = useCallback((text: string) => {
    categoryManuallyChanged.current = false; // Allow autofill when user changes name
    setFormState((prev) => ({ ...prev, taskName: text }));
  }, []);

  /**
   * Handle time to complete input change
   */
  const handleTimeToCompleteChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: text }));
  }, []);

  /**
   * Handle date selection from calendar picker
   */
  const handleDateSelect = useCallback((date: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: date }));
    setIsCalendarModalVisible(false);
  }, []);

  /**
   * Handle estimated minutes input change
   */
  const handleEstimatedMinutesChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, estimatedMinutes: text }));
  }, []);

  /**
   * Handle number of subtasks change
   */
  const handleNumSubtasksChange = useCallback(
    (value: number) => {
      if (value < 1) value = 1;
      if (value > 10) value = 10; // limit to 10 subtasks

      const currentSubtasks = formState.subtasks;
      const newSubtasks: Subtask[] = [];

      // Keep existing subtasks and add new ones if needed
      for (let i = 0; i < value; i++) {
        if (currentSubtasks[i]) {
          newSubtasks.push(currentSubtasks[i]);
        } else {
          newSubtasks.push({
            id: `subtask-${i}-${Date.now()}`,
            title: "",
            description: "",
            minutes: "",
            index: i + 1,
          });
        }
      }

      setFormState((prev) => ({ ...prev, numSubtasks: value, subtasks: newSubtasks }));
    },
    [formState.subtasks],
  );

  /**
   * Update a specific subtask
   */
  const updateSubtask = useCallback((index: number, field: keyof Subtask, value: any) => {
    setFormState((prev) => {
      const updatedSubtasks = [...prev.subtasks];
      updatedSubtasks[index] = {
        ...updatedSubtasks[index],
        [field]: value,
      };
      return { ...prev, subtasks: updatedSubtasks };
    });
  }, []);

  /**
   * Handle effort slider change
   */
  const handleEffortChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, effort: value }));
  }, []);

  /**
   * Handle importance slider change
   */
  const handleImportanceChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, importance: value }));
  }, []);

  /**
   * Handle category selection
   */
  const handleCategorySelect = useCallback((categoryKey: string) => {
    categoryManuallyChanged.current = true; // Mark as manually changed
    setFormState((prev) => ({ ...prev, category: categoryKey }));
  }, []);

  /**
   * Handle description input change
   */
  const handleDescriptionChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, description: text }));
  }, []);

  /**
   * Add a tag to the tag list
   */
  const handleAddTag = useCallback(() => {
    if (tagInput.trim() && !formState.tags.includes(tagInput.trim())) {
      setFormState((prev) => ({
        ...prev,
        tags: [...prev.tags, tagInput.trim()],
      }));
      setTagInput("");
    }
  }, [tagInput, formState.tags]);

  /**
   * Remove a tag from the tag list
   */
  const handleRemoveTag = useCallback((tagToRemove: string) => {
    setFormState((prev) => ({
      ...prev,
      tags: prev.tags.filter((tag) => tag !== tagToRemove),
    }));
  }, []);

  /**
   * Handle task deletion - Delete task via API
   */
  const handleDeleteTask = useCallback(() => {
    if (!taskId) {
      setPopupInfo({ title: "Error", message: "Task ID is missing. Unable to delete task." });
      return;
    }

    setPopupInfo({
      title: "Delete Task",
      message: "Are you sure you want to delete this task? This action cannot be undone.",
      confirmAction: async () => {
        setIsLoading(true);
        try {
          const success = await deleteTask(taskId);

          if (success) {
            notifyTaskUpdate({ taskId });
            setActiveTab("calendar");
          } else {
            setPopupInfo({ title: "Error", message: "Failed to delete task. Please try again." });
          }
        } catch (error) {
          setPopupInfo({ title: "Error", message: `Failed to delete task: ${error instanceof Error ? error.message : "Unknown error"}` });
        } finally {
          setIsLoading(false);
        }
      },
    });
  }, [taskId, setActiveTab, notifyTaskUpdate]);

  /**
   * Handle form submission - Update task via API
   */
  const handleUpdateTask = useCallback(async () => {
    // Validate required fields
    if (!formState.taskName.trim()) {
      setPopupInfo({ title: "Validation Error", message: "Please enter a task name" });
      return;
    }

    if (!formState.timeToComplete.trim()) {
      setPopupInfo({ title: "Validation Error", message: "Please select a date to complete" });
      return;
    }

    if (!taskId) {
      setPopupInfo({ title: "Error", message: "Task ID is missing. Unable to update task." });
      return;
    }

    setIsLoading(true);
    try {
      // Prepare subtasks data
      const subtasksData = formState.subtasks
        .filter((st) => st.title.trim()) // Only include subtasks with titles
        .map((st, idx) => ({
          id: st.id,
          title: st.title,
          description: st.description || undefined,
          minutes: st.minutes ? parseInt(st.minutes, 10) : undefined,
          index: idx + 1,
        }));

      // Determine task type based on number of parts and time distribution
      let taskType: "perfect" | "in_parts" | "leaky" = "perfect";
      let chunkCount: number | undefined = undefined;

      if (formState.numSubtasks > 1) {
        // Check if subtasks have different durations (leaky task)
        const subtaskMinutes = formState.subtasks
          .map((st) => (st.minutes ? parseInt(st.minutes, 10) : 0))
          .filter((m) => m > 0);

        if (subtaskMinutes.length >= 2) {
          const allSame = subtaskMinutes.every((m) => m === subtaskMinutes[0]);
          taskType = allSame ? "in_parts" : "leaky";
        } else {
          taskType = "in_parts";
        }
        chunkCount = formState.numSubtasks;
      }

      // Build update payload
      const updates: any = {
        taskname: formState.taskName,
        description: formState.description || "",
        category: formState.category,
        importance: formState.importance,
        effort: formState.effort,
        dueDate: formState.timeToComplete,
        estimatedDuration: formState.estimatedMinutes ? parseInt(formState.estimatedMinutes, 10) : undefined,
        tags: formState.tags.length > 0 ? formState.tags : [],
        taskType,
        chunkCount,
      };

      // Only include subtasks if there are actual parts
      if (subtasksData.length > 0) {
        updates.subtasks = subtasksData;
      }

      const updatedTask = await updateTask(taskId, updates);

      if (updatedTask) {
        notifyTaskUpdate({ taskId });
        setPopupInfo({ title: "Success!", message: "Task updated successfully", navigateOnClose: true });
      } else {
        setPopupInfo({ title: "Error", message: "Failed to update task. Please try again." });
      }
    } catch (error) {
      setPopupInfo({ title: "Error", message: `Failed to update task: ${error instanceof Error ? error.message : "Unknown error"}` });
    } finally {
      setIsLoading(false);
    }
  }, [formState, taskId, notifyTaskUpdate, setActiveTab]);

  const { dimensions } = useLayout();

  // Show loading spinner while fetching task data
  if (isFetching) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={COLORS.primary1} />
          <AppText style={styles.loadingText}>Loading task...</AppText>
        </View>
      </SafeAreaView>
    );
  }

  // Show error state if task couldn't be loaded
  if (fetchError) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <AppText style={styles.errorText}>{fetchError}</AppText>
          <AppButton
            title="Go Back"
            onPress={() => setActiveTab("calendar")}
            mode="filled"
            color="primary1"
            width="60%"
          />
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[
          styles.contentContainer,
          { paddingTop: (dimensions.headerHeight || SPACING.xlg * 3) + SPACING.md },
        ]}
        scrollIndicatorInsets={{ top: dimensions.headerHeight || SPACING.xlg * 3, bottom: NAVBAR_HEIGHT }}
      >
        {/* Task Details Box */}
        <Box title="TASK DETAILS" style={styles.boxContent}>
          {/* Task Name Input */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Task Name</AppText>
            <Input placeholder="Your Task" value={formState.taskName} onChangeText={handleTaskNameChange} type="text" />
          </View>

          {/* Time to Complete Input with Calendar Icon */}
          <View style={styles.formField}>
            <View style={styles.timeToCompleteLabelContainer}>
              <AppText style={styles.label}>Time to Complete</AppText>
            </View>
            <View style={styles.timeToCompleteWrapper}>
              <View style={styles.timeToCompleteInputContainer}>
                <Input
                  placeholder="Your Task"
                  value={formState.timeToComplete}
                  onChangeText={handleTimeToCompleteChange}
                  type="text"
                  editable={false}
                />
                <Pressable
                  style={styles.calendarButton}
                  onPress={() => setIsCalendarModalVisible(!isCalendarModalVisible)}
                >
                  {ICONS.calendar &&
                    React.createElement(ICONS.calendar, {
                      size: 24,
                      color: COLORS.primary1,
                    })}
                </Pressable>
              </View>

              {/* Inline Calendar Dropdown */}
              {isCalendarModalVisible && (
                <View style={styles.inlineCalendarContainer}>
                  <CalendarPicker onDateSelect={handleDateSelect} selectedDate={formState.timeToComplete} />
                </View>
              )}
            </View>
          </View>

          {/* Effort and Importance Sliders */}
          <View style={styles.slidersContainer}>
            <View style={[styles.sliderWrapper, { flex: 1, marginRight: SPACING.md }]}>
              <SliderComponent
                value={formState.effort}
                onValueChange={handleEffortChange}
                min={1}
                max={5}
                step={1}
                label="Effort"
                trackColor={COLORS.lightGray}
                TrackThumbColor={getImportanceColor(formState.effort)}
                valueDescriptions={{
                  1: "Very Easy",
                  2: "Easy",
                  3: "Moderate",
                  4: "Hard",
                  5: "Very Hard",
                }}
              />
            </View>

            <View style={[styles.sliderWrapper, { flex: 1 }]}>
              <SliderComponent
                value={formState.importance}
                onValueChange={handleImportanceChange}
                min={1}
                max={5}
                step={1}
                label="Importance"
                trackColor={COLORS.lightGray}
                TrackThumbColor={getImportanceColor(formState.importance)}
                valueDescriptions={{
                  1: "Low",
                  2: "Below Avg",
                  3: "Average",
                  4: "Above Avg",
                  5: "Critical",
                }}
              />
            </View>
          </View>

          {/* Task Category Dropdown */}
          <View style={styles.formField}>
            <AppText style={styles.label}>Task Category</AppText>
            <CategoryPicker
              value={formState.category as any}
              onChange={(v) => handleCategorySelect(v)}
            />
          </View>

          {/* Task Tags Section */}
          <View style={styles.formField}>
            <View style={styles.tagsLabelContainer}>
              <AppText style={styles.label}>Task Tags</AppText>
            </View>

            <View style={styles.tagInputContainer}>
              <Input placeholder="Your name" value={tagInput} onChangeText={setTagInput} type="text" />
              <Pressable style={styles.addTagButton} onPress={handleAddTag}>
                <AppText variant="title3" style={styles.addTagButtonText}>
                  +
                </AppText>
              </Pressable>
            </View>

            {/* Rendered Tags */}
            <TagsBelow selected={formState.tags} onRemove={handleRemoveTag} />
          </View>

          {/* Task Description Textarea */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Task Description</AppText>
            <Input
              placeholder="Your Task"
              value={formState.description}
              onChangeText={handleDescriptionChange}
              type="longtext"
              multiline
              numberOfLines={6}
            />
          </View>
        </Box>

        {/* Spacer between boxes */}
        <View style={{ height: SPACING.lg }} />

        {/* Additional Task Details Box */}
        <Box title="ADDITIONAL DETAILS" style={styles.boxContent}>
          {/* Estimated Minutes Input */}
          <View style={styles.formField}>
            <AppText style={styles.customLabel}>Estimated Minutes</AppText>
            <Input
              placeholder="e.g., 30"
              value={formState.estimatedMinutes}
              onChangeText={handleEstimatedMinutesChange}
              type="number"
            />
          </View>

          {/* Number of Subtasks */}
          <View style={styles.formField}>
            <AppText style={styles.label}>Split Task Into Parts</AppText>
            <View style={styles.subtaskCounterContainer}>
              <Pressable
                style={styles.counterButton}
                onPress={() => handleNumSubtasksChange(Math.max(1, formState.numSubtasks - 1))}
              >
                <AppText style={styles.counterButtonText}>−</AppText>
              </Pressable>
              <View style={styles.counterDisplay}>
                <AppText style={styles.counterText}>{formState.numSubtasks}</AppText>
              </View>
              <Pressable
                style={styles.counterButton}
                onPress={() => handleNumSubtasksChange(formState.numSubtasks + 1)}
              >
                <AppText style={styles.counterButtonText}>+</AppText>
              </Pressable>
            </View>
          </View>

          {/* Subtasks Section - Only show if numSubtasks >= 2 */}
          {formState.numSubtasks >= 2 && (
            <View style={styles.subtasksSection}>
              <AppText style={[styles.label, { marginBottom: SPACING.md }]}>Define Subtasks</AppText>
              {formState.subtasks.map((subtask, index) => (
                <View key={subtask.id} style={styles.subtaskCard}>
                  <AppText style={styles.subtaskHeader}>Part {index + 1}</AppText>

                  {/* Subtask Title */}
                  <View style={styles.formField}>
                    <AppText style={styles.customLabel}>Part Name</AppText>
                    <Input
                      placeholder="e.g., Planning"
                      value={subtask.title}
                      onChangeText={(text) => updateSubtask(index, "title", text)}
                      type="text"
                    />
                  </View>

                  {/* Subtask Description */}
                  <View style={styles.formField}>
                    <AppText style={styles.customLabel}>Part Description</AppText>
                    <Input
                      placeholder="Describe this part..."
                      value={subtask.description}
                      onChangeText={(text) => updateSubtask(index, "description", text)}
                      type="longtext"
                      multiline
                      numberOfLines={2}
                    />
                  </View>

                  {/* Subtask Estimated Minutes */}
                  <View style={styles.formField}>
                    <Input
                      label="Estimated Minutes"
                      placeholder="e.g., 15"
                      value={subtask.minutes}
                      onChangeText={(text) => updateSubtask(index, "minutes", text)}
                      type="number"
                    />
                  </View>
                </View>
              ))}
            </View>
          )}
        </Box>

        {/* Update Task Button */}
        <View style={styles.buttonContainer}>
          <AppButton
            title={isLoading ? "UPDATING..." : "UPDATE TASK"}
            onPress={handleUpdateTask}
            mode="filled"
            color="#2ecc71"
            icon={isLoading ? undefined : "check"}
            iconPosition="right"
            width="100%"
            disabled={isLoading}
          />
        </View>

        {/* Action Row: Discard + Delete */}
        <View style={styles.actionRow}>
          <AppButton
            title="Discard Changes"
            onPress={() => setActiveTab("calendar")}
            mode="filled"
            color="lightGray"
            width="48%"
          />

          <AppButton
            title="DELETE TASK"
            onPress={handleDeleteTask}
            mode="filled"
            color="primary7"
            width="48%"
            disabled={isLoading}
          />
        </View>
      </ScrollView>

      {/* Popup / Alert */}
      <PopupBox
        visible={popupInfo !== null}
        onClose={() => setPopupInfo(null)}
        title={popupInfo?.title ?? ""}
        titleColor={COLORS.primary1}
      >
        <AppText style={{ color: COLORS.darkGray, marginBottom: SPACING.lg }}>
          {popupInfo?.message}
        </AppText>
        {popupInfo?.confirmAction ? (
          <View style={{ flexDirection: "row", gap: SPACING.md }}>
            <AppButton
              title="Cancel"
              mode="filled"
              color="lightGray"
              onPress={() => setPopupInfo(null)}
              width="48%"
            />
            <AppButton
              title="Delete"
              mode="filled"
              color="primary7"
              onPress={() => { const action = popupInfo?.confirmAction; setPopupInfo(null); if (action) action(); }}
              width="48%"
            />
          </View>
        ) : (
          <AppButton
            title="OK"
            mode="filled"
            color="primary1"
            onPress={() => { const nav = popupInfo?.navigateOnClose; setPopupInfo(null); if (nav) setActiveTab("calendar"); }}
            width="100%"
          />
        )}
      </PopupBox>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white3,
    flexDirection: "column",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: SPACING.lg,
  },
  loadingText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.darkGray,
    marginTop: SPACING.md,
  },
  errorText: {
    fontSize: FONT_SIZES.md,
    color: "#D32F2F",
    textAlign: "center",
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.xlg,
  },
  contentContainer: {
    padding: SPACING.md,
    paddingBottom: NAVBAR_HEIGHT + SPACING.xlg,
  },
  headerIconButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  boxContent: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.lg,
    overflow: "visible",
  },
  formField: {
    marginBottom: SPACING.md,
    overflow: "visible",
  },
  slidersContainer: {
    flexDirection: "row",
    marginBottom: SPACING.sm,
    gap: SPACING.sm,
  },
  sliderWrapper: {
    gap: SPACING.sm,
  },
  sliderLabel: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  label: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  customLabel: {
    fontWeight: "400",
    color: COLORS.darkGray,
    marginBottom: 4,
  },
  timeToCompleteLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: 4,
  },
  timeToCompleteInputContainer: {
    position: "relative",
    marginBottom: 3,
  },
  timeToCompleteWrapper: {
    overflow: "visible",
  },
  inlineCalendarContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
    overflow: "hidden",
    ...SHADOWS.card,
  },
  inlineCalendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.brightP1,
  },
  inlineCalendarTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "400",
    color: COLORS.primary1,
  },
  inlineCalendarClose: {
    fontSize: FONT_SIZES.lg,
    color: COLORS.darkGray,
    fontWeight: "400",
  },
  inlineCalendarContent: {
    padding: SPACING.md,
    minHeight: 250,
    justifyContent: "center",
    alignItems: "center",
  },
  inlineCalendarPlaceholder: {
    color: COLORS.lightGray,
    fontSize: FONT_SIZES.md,
  },
  calendarButton: {
    position: "absolute",
    right: SPACING.sm,
    top: "50%",
    transform: [{ translateY: -22 }],
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  subtaskCounterContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginTop: SPACING.sm,
  },
  counterButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: COLORS.primary1,
    justifyContent: "center",
    alignItems: "center",
  },
  counterButtonText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.lg,
    fontWeight: "bold",
  },
  counterDisplay: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    alignItems: "center",
    ...SHADOWS.card,
  },
  counterText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "600",
    color: COLORS.primary1,
  },
  subtasksSection: {
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  subtaskCard: {
    backgroundColor: COLORS.white2,
    borderRadius: 12,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary1,
  },
  subtaskHeader: {
    fontSize: FONT_SIZES.md,
    fontWeight: "600",
    color: COLORS.primary1,
    marginBottom: SPACING.md,
  },
  tagsLabelContainer: {
    // marginBottom: 1,
  },
  tagInputContainer: {
    position: "relative",
    marginBottom: 3,
  },
  addTagButton: {
    position: "absolute",
    right: SPACING.sm,
    top: "50%",
    transform: [{ translateY: -22 }],
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  addTagButtonText: {
    color: COLORS.primary1,
    fontSize: FONT_SIZES.md,
    fontWeight: "bold",
  },
  taskPartsGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: SPACING.lg,
  },
  taskPartItem: {
    alignItems: "center",
    gap: SPACING.sm,
  },
  taskPartIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: COLORS.white3,
    justifyContent: "center",
    alignItems: "center",
  },
  taskPartLabel: {
    textAlign: "center",
    fontSize: FONT_SIZES.sm,
    color: COLORS.darkGray,
    maxWidth: 80,
  },
  buttonContainer: {
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
  },
  actionRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: SPACING.md,
    paddingHorizontal: SPACING.md,
    marginTop: SPACING.md,
  },
});

export default EditTask;
