/**
 * EditTask Screen
 *
 * Thin orchestration screen for editing an existing task.
 * All UI sections are extracted into dedicated components:
 *
 *  ┌─────────────────────────────────────────────────────────────────────┐
 *  │  TaskDetailsSection      Task name, due date, sliders, category,   │
 *  │                          tags, description                          │
 *  ├─────────────────────────────────────────────────────────────────────┤
 *  │  AdditionalDetailsSection  Estimated minutes, subtask parts editor  │
 *  ├─────────────────────────────────────────────────────────────────────┤
 *  │  TaskScheduleEditor      Manual / auto schedule (self-contained)   │
 *  ├─────────────────────────────────────────────────────────────────────┤
 *  │  TaskActionButtons       UPDATE / Discard / DELETE                  │
 *  └─────────────────────────────────────────────────────────────────────┘
 */

import React, { useState, useCallback, useEffect, useRef } from "react";
import { View, StyleSheet, ScrollView, SafeAreaView, TouchableOpacity, ActivityIndicator } from "react-native";
import { COLORS, SPACING, FONT_SIZES, ICON_SIZES } from "../theme";

// ── Common components ─────────────────────────────────────────────────────────
import AppText from "../components/common/AppText";
import AppButton from "../components/common/AppButton";
import PopupBox from "../components/common/PopupBox";

// ── Extracted task-form section components ────────────────────────────────────
import TaskDetailsSection from "../components/special/task/TaskDetailsSection";
import TimeAndPartsSection from "../components/special/task/TimeAndPartsSection";
import TaskScheduleEditor from "../components/special/task/TaskScheduleEditor";
import TaskActionButtons from "../components/special/task/TaskActionButtons";
import { toLocalDateStr, toLocalTimeStr } from "../components/special/task/TaskScheduleEditor";
import type { TaskFormState, Subtask, EditableSession } from "../components/special/task/taskFormTypes";

// ── Icons and context ─────────────────────────────────────────────────────────
import { ICONS } from "../components/icons/icons";
import { useNavigation } from "../context/NavigationContext";
import { useTaskContext } from "../context/TaskContext";
import { useLayout } from "../context/LayoutContext";

// ── Services ──────────────────────────────────────────────────────────────────
import {
  getTaskById,
  updateTask,
  deleteTask,
  suggestCategory,
  getTaskSessions,
} from "../services/taskService";

const NAVBAR_HEIGHT = 96;



// ─────────────────────────────────────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────────────────────────────────────

const EditTask: React.FC<{ taskId?: string }> = ({ taskId = "" }) => {
  const { setHeaderConfig, setActiveTab } = useNavigation();
  const { notifyTaskUpdate } = useTaskContext();
  const { dimensions } = useLayout();

  // ── Form state ────────────────────────────────────────────────────────────
  const [formState, setFormState] = useState<TaskFormState>({
    taskName: "",
    timeToComplete: "",
    effort: 3,
    importance: 3,
    category: "",
    tags: [],
    description: "",
    estimatedMinutes: "",
    numSubtasks: 1,
    subtasks: [],
  });

  const [tagInput, setTagInput] = useState("");
  const [isCalendarVisible, setIsCalendarVisible] = useState(false);

  // ── UI / loading state ────────────────────────────────────────────────────
  const [isLoading, setIsLoading] = useState(false);
  const [isFetching, setIsFetching] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [popupInfo, setPopupInfo] = useState<{
    title: string;
    message: string;
    navigateOnClose?: boolean;
    confirmAction?: () => void;
  } | null>(null);

  // ── Schedule initial state (seeded from API; owned by TaskScheduleEditor after mount) ──
  const [initialSessions, setInitialSessions] = useState<EditableSession[]>([]);
  const [initialIsManual, setInitialIsManual] = useState(false);
  const [sessionsLoading, setSessionsLoading] = useState(false);

  // ── Refs ──────────────────────────────────────────────────────────────────
  const categoryManuallyChanged = useRef(false);
  const hasLoadedTask = useRef(false);
  /** Tracks the last subcategory tag injected by the AI autofill so we only
   * replace that one tag instead of wiping all user-added tags. */
  const autoGeneratedTag = useRef<string | null>(null);

  // Use the shared Header via NavigationContext so spacing matches other screens
  useEffect(() => {
    const handleBackPress = () => {
      setActiveTab("calendar");
    };

    setHeaderConfig({
      title: "Edit Task",
      show: true,
      icon: ICONS.edit,
      leftElement: (
        <TouchableOpacity onPress={handleBackPress} style={styles.headerIconButton}>
          {ICONS.left && React.createElement(ICONS.left, { size: ICON_SIZES.md, color: COLORS.primary1 })}
        </TouchableOpacity>
      ),
      rightElement: (
        <View style={styles.headerRight}>
          {ICONS.edit && React.createElement(ICONS.edit, { size: ICON_SIZES.md, color: COLORS.primary1 })}
        </View>
      ),
    });

    return () => {
      // Clean up: hide header for other flows that expect no header
      setHeaderConfig({ show: false });
    };
  }, [setHeaderConfig, setActiveTab]);

  // Load task data from API when the screen mounts or taskId changes
  useEffect(() => {
    if (!taskId) {
      setIsFetching(false);
      setFetchError("No task ID provided.");
      return;
    }

    let cancelled = false;

    const loadTask = async () => {
      setIsFetching(true);
      setFetchError(null);
      try {
        const task = await getTaskById(taskId);
        if (cancelled) return;

        if (!task) {
          setFetchError("Task not found.");
          setIsFetching(false);
          return;
        }

        // Extract date portion from dueDate (YYYY-MM-DD).
        // Use UTC getters so a midnight-UTC date is never shifted to the previous day
        // for users in UTC− timezones (e.g. 2024-12-15T00:00Z → local "Dec 14" in UTC-5).
        let dateStr = "";
        if (task.dueDate) {
          const d = new Date(task.dueDate);
          dateStr = d.toISOString().slice(0, 10); // "YYYY-MM-DD" in UTC, matching server storage
        }

        // Build subtask form state from API subtasks
        const apiSubtasks = task.subtasks || (task as any).subTasks || [];
        const formSubtasks: Subtask[] = apiSubtasks.map((st: any, idx: number) => ({
          id: st._id || st.id || `subtask-${idx}-${Date.now()}`,
          title: st.title || "",
          description: st.description || "",
          minutes: st.minutes ? String(st.minutes) : "",
          index: st.index ?? idx + 1,
        }));

        const numSubtasks = formSubtasks.length > 0 ? formSubtasks.length : 1;

        // Build tags from task.tags
        const tags: string[] = [];
        if (task.tags && Array.isArray(task.tags)) {
          tags.push(...task.tags);
        }

        setFormState({
          taskName: task.taskname || "",
          timeToComplete: dateStr,
          effort: task.effort ?? 3,
          importance: task.importance ?? 3,
          category: task.category || "",
          tags,
          description: task.description || "",
          estimatedMinutes: task.estimatedDuration ? String(task.estimatedDuration) : "",
          numSubtasks,
          subtasks: formSubtasks,
        });

        hasLoadedTask.current = true;
        categoryManuallyChanged.current = true; // Prevent autofill from overwriting loaded category

        // Load the task's current scheduled sessions for the schedule editor
        setSessionsLoading(true);
        try {
          const sessionsData = await getTaskSessions(taskId);
          if (!cancelled && sessionsData) {
            setInitialIsManual(sessionsData.manualSchedule);
            setInitialSessions(
              (sessionsData.sessions ?? [])
                .filter((s) => s.status !== "completed")
                .map((s) => ({
                  id: s._id,
                  date: toLocalDateStr(s.start),
                  startTime: toLocalTimeStr(s.start),
                  endTime: toLocalTimeStr(s.end),
                  subtaskIndex: s.subtaskIndex,
                })),
            );
          }
        } catch (_) {
          // non-fatal — schedule editor simply shows empty
        } finally {
          if (!cancelled) setSessionsLoading(false);
        }
      } catch (error) {
        if (!cancelled) {
          setFetchError(error instanceof Error ? error.message : "Failed to load task.");
        }
      } finally {
        if (!cancelled) {
          setIsFetching(false);
        }
      }
    };

    loadTask();

    return () => {
      cancelled = true;
    };
  }, [taskId]);

  // Debounced autofill for category and subcategory based on task name
  // Only runs when user manually changes the task name (not during initial load)
  useEffect(() => {
    if (!formState.taskName.trim() || !hasLoadedTask.current) {
      return; // Don't autofill if task name is empty or we haven't loaded yet
    }

    // Don't autofill if category was manually changed or set by loading
    if (categoryManuallyChanged.current) {
      return;
    }

    const timeoutId = setTimeout(async () => {
      try {
        const suggestion = await suggestCategory(formState.taskName);

        if (suggestion && !categoryManuallyChanged.current) {
          const prevAutoTag = autoGeneratedTag.current;
          const newAutoTag = suggestion.subCategory ?? null;

          setFormState((prev) => {
            // Remove the previously-injected AI tag (if any), keep all user-added tags
            const userTags = prevAutoTag
              ? prev.tags.filter((t) => t !== prevAutoTag)
              : prev.tags;
            const nextTags = newAutoTag && !userTags.includes(newAutoTag)
              ? [newAutoTag, ...userTags]
              : userTags;
            return {
              ...prev,
              category: suggestion.category,
              tags: nextTags,
            };
          });

          autoGeneratedTag.current = newAutoTag;
        }
      } catch (error) {
        console.warn("Failed to auto-suggest category:", error);
      }
    }, 800); // Debounce for 800ms

    return () => clearTimeout(timeoutId);
  }, [formState.taskName]);

  /**
   * Handle task name input change
   */
  const handleTaskNameChange = useCallback((text: string) => {
    categoryManuallyChanged.current = false; // Allow autofill when user changes name
    setFormState((prev) => ({ ...prev, taskName: text }));
  }, []);

  /**
   * Handle time to complete input change
   */
  const handleTimeToCompleteChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: text }));
  }, []);

  /**
   * Handle date selection from calendar picker
   */
  const handleDateSelect = useCallback((date: string) => {
    setFormState((prev) => ({ ...prev, timeToComplete: date }));
    setIsCalendarVisible(false);
  }, []);

  /**
   * Handle estimated minutes input change
   */
  const handleEstimatedMinutesChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, estimatedMinutes: text }));
  }, []);

  /**
   * Handle number of subtasks change
   */
  const handleNumSubtasksChange = useCallback(
    (value: number) => {
      if (value < 1) value = 1;
      if (value > 10) value = 10; // limit to 10 subtasks

      const currentSubtasks = formState.subtasks;
      const newSubtasks: Subtask[] = [];

      // Keep existing subtasks and add new ones if needed
      for (let i = 0; i < value; i++) {
        if (currentSubtasks[i]) {
          newSubtasks.push(currentSubtasks[i]);
        } else {
          newSubtasks.push({
            id: `subtask-${i}-${Date.now()}`,
            title: "",
            description: "",
            minutes: "",
            index: i + 1,
          });
        }
      }

      setFormState((prev) => ({ ...prev, numSubtasks: value, subtasks: newSubtasks }));
    },
    [formState.subtasks],
  );

  /**
   * Update a specific subtask
   */
  const updateSubtask = useCallback((index: number, field: keyof Subtask, value: any) => {
    setFormState((prev) => {
      const updatedSubtasks = [...prev.subtasks];
      updatedSubtasks[index] = {
        ...updatedSubtasks[index],
        [field]: value,
      };
      return { ...prev, subtasks: updatedSubtasks };
    });
  }, []);

  /**
   * Handle effort slider change
   */
  const handleEffortChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, effort: value }));
  }, []);

  /**
   * Handle importance slider change
   */
  const handleImportanceChange = useCallback((value: number) => {
    setFormState((prev) => ({ ...prev, importance: value }));
  }, []);

  /**
   * Handle category selection
   */
  const handleCategorySelect = useCallback((categoryKey: string) => {
    categoryManuallyChanged.current = true; // Mark as manually changed
    setFormState((prev) => ({ ...prev, category: categoryKey }));
  }, []);

  /**
   * Handle description input change
   */
  const handleDescriptionChange = useCallback((text: string) => {
    setFormState((prev) => ({ ...prev, description: text }));
  }, []);

  /**
   * Add a tag to the tag list
   */
  const handleAddTag = useCallback(() => {
    if (tagInput.trim() && !formState.tags.includes(tagInput.trim())) {
      setFormState((prev) => ({
        ...prev,
        tags: [...prev.tags, tagInput.trim()],
      }));
      setTagInput("");
    }
  }, [tagInput, formState.tags]);

  /**
   * Remove a tag from the tag list
   */
  const handleRemoveTag = useCallback((tagToRemove: string) => {
    setFormState((prev) => ({
      ...prev,
      tags: prev.tags.filter((tag) => tag !== tagToRemove),
    }));
  }, []);

  /**
   * Handle task deletion - Delete task via API
   */
  const handleDeleteTask = useCallback(() => {
    if (!taskId) {
      setPopupInfo({ title: "Error", message: "Task ID is missing. Unable to delete task." });
      return;
    }

    setPopupInfo({
      title: "Delete Task",
      message: "Are you sure you want to delete this task? This action cannot be undone.",
      confirmAction: async () => {
        setIsLoading(true);
        try {
          const success = await deleteTask(taskId);

          if (success) {
            notifyTaskUpdate({ taskId });
            setActiveTab("calendar");
          } else {
            setPopupInfo({ title: "Error", message: "Failed to delete task. Please try again." });
          }
        } catch (error) {
          setPopupInfo({ title: "Error", message: `Failed to delete task: ${error instanceof Error ? error.message : "Unknown error"}` });
        } finally {
          setIsLoading(false);
        }
      },
    });
  }, [taskId, setActiveTab, notifyTaskUpdate]);

  /**
   * Handle form submission - Update task via API
   */
  const handleUpdateTask = useCallback(async () => {
    // Validate required fields
    if (!formState.taskName.trim()) {
      setPopupInfo({ title: "Validation Error", message: "Please enter a task name" });
      return;
    }

    if (!formState.timeToComplete.trim()) {
      setPopupInfo({ title: "Validation Error", message: "Please select a date to complete" });
      return;
    }

    if (!taskId) {
      setPopupInfo({ title: "Error", message: "Task ID is missing. Unable to update task." });
      return;
    }

    setIsLoading(true);
    try {
      // Prepare subtasks data
      const subtasksData = formState.subtasks
        .filter((st) => st.title.trim()) // Only include subtasks with titles
        .map((st, idx) => ({
          id: st.id,
          title: st.title,
          description: st.description || undefined,
          minutes: st.minutes ? parseInt(st.minutes, 10) : undefined,
          index: idx + 1,
        }));

      // Determine task type based on number of parts and time distribution
      let taskType: "perfect" | "in_parts" | "leaky" = "perfect";
      let chunkCount: number | undefined = undefined;

      if (formState.numSubtasks > 1) {
        // Check if subtasks have different durations (leaky task)
        const subtaskMinutes = formState.subtasks
          .map((st) => (st.minutes ? parseInt(st.minutes, 10) : 0))
          .filter((m) => m > 0);

        if (subtaskMinutes.length >= 2) {
          const allSame = subtaskMinutes.every((m) => m === subtaskMinutes[0]);
          taskType = allSame ? "in_parts" : "leaky";
        } else {
          taskType = "in_parts";
        }
        chunkCount = formState.numSubtasks;
      }

      // Build update payload
      const updates: any = {
        taskname: formState.taskName,
        description: formState.description || "",
        category: formState.category,
        importance: formState.importance,
        effort: formState.effort,
        dueDate: formState.timeToComplete,
        estimatedDuration: formState.estimatedMinutes ? parseInt(formState.estimatedMinutes, 10) : undefined,
        tags: formState.tags.length > 0 ? formState.tags : [],
        taskType,
        chunkCount,
      };

      // Only include subtasks if there are actual parts
      if (subtasksData.length > 0) {
        updates.subtasks = subtasksData;
      }

      const updatedTask = await updateTask(taskId, updates);

      if (updatedTask) {
        notifyTaskUpdate({ taskId });
        setPopupInfo({ title: "Success!", message: "Task updated successfully", navigateOnClose: true });
      } else {
        setPopupInfo({ title: "Error", message: "Failed to update task. Please try again." });
      }
    } catch (error) {
      setPopupInfo({ title: "Error", message: `Failed to update task: ${error instanceof Error ? error.message : "Unknown error"}` });
    } finally {
      setIsLoading(false);
    }
  }, [formState, taskId, notifyTaskUpdate]);

  // Show loading spinner while fetching task data
  if (isFetching) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={COLORS.primary1} />
          <AppText style={styles.loadingText}>Loading task...</AppText>
        </View>
      </SafeAreaView>
    );
  }

  // Show error state if task couldn't be loaded
  if (fetchError) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <AppText style={styles.errorText}>{fetchError}</AppText>
          <AppButton
            title="Go Back"
            onPress={() => setActiveTab("calendar")}
            mode="filled"
            color="primary1"
            width="60%"
          />
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[
          styles.contentContainer,
          { paddingTop: (dimensions.headerHeight || SPACING.xlg * 3) + SPACING.md },
        ]}
        scrollIndicatorInsets={{ top: dimensions.headerHeight || SPACING.xlg * 3, bottom: NAVBAR_HEIGHT }}
      >
        <TaskDetailsSection
          taskName={formState.taskName}
          timeToComplete={formState.timeToComplete}
          effort={formState.effort}
          importance={formState.importance}
          category={formState.category}
          tags={formState.tags}
          description={formState.description}
          tagInput={tagInput}
          isCalendarVisible={isCalendarVisible}
          onTaskNameChange={handleTaskNameChange}
          onTimeToCompleteChange={handleTimeToCompleteChange}
          onDateSelect={handleDateSelect}
          onCalendarToggle={() => setIsCalendarVisible((v) => !v)}
          onEffortChange={handleEffortChange}
          onImportanceChange={handleImportanceChange}
          onCategorySelect={handleCategorySelect}
          onDescriptionChange={handleDescriptionChange}
          onTagInputChange={setTagInput}
          onAddTag={handleAddTag}
          onRemoveTag={handleRemoveTag}
        />

        <View style={{ height: SPACING.lg }} />

        <TimeAndPartsSection
          estimatedMinutes={formState.estimatedMinutes}
          numSubtasks={formState.numSubtasks}
          subtasks={formState.subtasks}
          onEstimatedMinutesChange={handleEstimatedMinutesChange}
          onNumSubtasksChange={handleNumSubtasksChange}
          onSubtaskUpdate={updateSubtask}
        />

        <View style={{ height: SPACING.lg }} />

        <TaskScheduleEditor
          taskId={taskId}
          initialSessions={initialSessions}
          initialIsManualSchedule={initialIsManual}
          isLoadingInitial={sessionsLoading}
          onPopup={(title, message) => setPopupInfo({ title, message })}
          onTaskUpdated={() => notifyTaskUpdate({ taskId })}
        />

        <TaskActionButtons
          onUpdate={handleUpdateTask}
          onDiscard={() => setActiveTab("calendar")}
          onDelete={handleDeleteTask}
          isUpdating={isLoading}
        />
      </ScrollView>

      {/* Popup / Alert */}
      <PopupBox
        visible={popupInfo !== null}
        onClose={() => setPopupInfo(null)}
        title={popupInfo?.title ?? ""}
        titleColor={COLORS.primary1}
      >
        <AppText style={{ color: COLORS.darkGray, marginBottom: SPACING.lg }}>
          {popupInfo?.message}
        </AppText>
        {popupInfo?.confirmAction ? (
          <View style={{ flexDirection: "row", gap: SPACING.md }}>
            <AppButton
              title="Cancel"
              mode="filled"
              color="lightGray"
              onPress={() => setPopupInfo(null)}
              width="48%"
            />
            <AppButton
              title="Delete"
              mode="filled"
              color="primary7"
              onPress={() => { const action = popupInfo?.confirmAction; setPopupInfo(null); if (action) action(); }}
              width="48%"
            />
          </View>
        ) : (
          <AppButton
            title="OK"
            mode="filled"
            color="primary1"
            onPress={() => { const nav = popupInfo?.navigateOnClose; setPopupInfo(null); if (nav) setActiveTab("calendar"); }}
            width="100%"
          />
        )}
      </PopupBox>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white3,
    flexDirection: "column",
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: SPACING.md,
    paddingBottom: NAVBAR_HEIGHT + SPACING.xlg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: SPACING.lg,
  },
  loadingText: {
    fontSize: FONT_SIZES.md,
    color: COLORS.darkGray,
    marginTop: SPACING.md,
  },
  errorText: {
    fontSize: FONT_SIZES.md,
    color: "#D32F2F",
    textAlign: "center",
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.xlg,
  },
  headerIconButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
});

export default EditTask;
